### ISSUE TITLE
How to compare database dump FILES?

### ISSUE THREAD

**Issue by COLABORATI** [DBDiff/DBDiff#13]
From what I undertstand reading the description this interesting tool can compare database schemas ony in live databases. I would like to compare schemas from database dumps that were generated with ```mysqldump``` - is this possible? 

Thanks for your attention!

**Comment by jasdeepkhalsa** [comment]
Hi @COLABORATI.

We had a similar question asked here: https://github.com/DBDiff/DBDiff/issues/3

Currently the only solution is to you get your SQL file added back into a temporary MySQL database on your laptop / machine in order to produce your migrations. You can always destroy that temporary database later :) The reason being that we can only connect to a MySQL database (at the moment) to produce migrations, and if we put in work to add this feature, behind the scenes we'd have to use a temporary database ourselves to do the migrations anyway since a file does not contain any structured data we can use to identity schema / data.
