### ISSUE TITLE
Diff with dump

### ISSUE THREAD

**Issue by CodingPeak** [DBDiff/DBDiff#23]
Hi there,

Are there any plans to compare a database structure with an already existing mysqldump (e.g. in a file)?

My temp solution to this would be to create the database from the dump and then use this tool, but that doesn't feel right.

I think the solution to this would only be a small change in code to make it possible.

**Comment by jasdeepkhalsa** [comment]
Lots of people have asked this, including #13 & #3.

I think you're right, the tool should be able to handle this, even if it means creating those temp tables in a MySQL database on your behalf.

However something like this may not be a small change in code as we have to deal with lots of cases & there's lots of unanswered questions:

* Which database should the temporary one be created in? Does the tool need a username and password to a database in order to do this?
* What happens when there's a lack of schema information to re-create tables for proper comparison e.g. when comparing a file to a database? Should it (a) fail fast, (b) try to do the potentially expensive comparison, (c) skips some of the database and/or table checks?
* What happens to those temporary database/tables afterwards?

**Comment by jhbsk** [comment]
We'll keep this in mind as a future feature or a bash script people can run, but currently this feature is too big to include into DBDiff, so closing this ticket for now
