### ISSUE TITLE
source db can use sql files?

### ISSUE THREAD

**Issue by dwdcth** [DBDiff/DBDiff#3]
Thanks for your great work!
Our  production dbs are only allowed  to access in local netwrok.
We dump developing dbs to sql files and restore  them to production dbs.
If source db can use sql files?

**Comment by jasdeepkhalsa** [comment]
Apologies for the delayed reply!

For database access, internally we are using Laravel's database connectivity module called `illuminate/database` which only supports `MySQL, Postgres, SQLite, and SQL Server`. As a result you would not be able to use DBDiff without the SQL file being inside a database.

Also, currently we're only supporting MySQL properly in order to see if this tool is really being demanded by the community first, and iron out any issues.

As a result, for your purposes, you may want to try to get your SQL file added into a temporary MySQL database on your laptop / machine in order to produce your migrations. You can always destroy that temporary database later :)

**Comment by dwdcth** [comment]
OK, a a temporary database maybe a solution.Thank you !
