### ISSUE TITLE
Approaches for same server or not

### ISSUE THREAD

**Issue by webian** [DBDiff/DBDiff#7]
Hi @jasdeepkhalsa,
I can't get the reason why you use 2 different approaches if the comparison is between same servers or different.
I mean this code in method getDiff of TableData:

```
if ($server1 == $server2) {
  return $this->localTableData->getDiff($table, $sourceKey);
} else {
  return $this->distTableData->getDiff($table, $sourceKey);
}
```

Please, can you help me to understand?

**Comment by jasdeepkhalsa** [comment]
I have to admit I didn't write the initial codebase, I wrote the specification and outsourced it because I never had the time to actually write the tool but I wanted to use it. It was always my intention to keep this as an open source tool & codebase.

So if I have to guess the reason it's probably that when it's the same server and thus a local database, there are other clever optimizations that we do in order to make the diff super fast across millions of rows. I would doubt these optimizations would work if the database is a remote one.

If you can dig into the codebase further to confirm whether this is the case, that would be great! :)
