### ISSUE TITLE
Failed comparison if a field is NULL

### ISSUE THREAD

**Issue by webian** [DBDiff/DBDiff#9]
If one of the fields of the analyzed record is NULL then MD5 returns NULL so even if 2 records are different they are considered equal: NULL = NULL
This happens in method getChangeDiff of class LocalTableData

**Comment by jasdeepkhalsa** [comment]
Nice edge case!

I suppose we'll have to look at how to get MD5 to give a result for NULL (perhaps it could work as a string), or just to handle NULL records specially

**Comment by jasdeepkhalsa** [comment]
Fixed in https://github.com/DBDiff/DBDiff/pull/12

**Comment by djshen-ponddy** [comment]
In getChangeDiff` of src/DB/Data/LocalTableData.php,
```php
        $result = $this->source->select(
           "SELECT * FROM (
                SELECT $columnsAas, $columnsBas, MD5(concat($columnsA)) AS hash1,
                MD5(concat($columnsB)) AS hash2 FROM {$db1}.{$table} as a 
                INNER JOIN {$db2}.{$table} as b  
                ON $keyCols
            ) t WHERE hash1 <> hash2");
```
if one of the columns is NULL, then the result of concat is NULL. For example,
```sql
mysql> SELECT CONCAT("a", NULL);
+-------------------+
| CONCAT("a", NULL) |
+-------------------+
| NULL              |
+-------------------+
1 row in set (0.03 sec)
```
Maybe it could be fixed by MySQL function [IFNULL](http://dev.mysql.com/doc/refman/5.7/en/control-flow-functions.html#function_ifnull) and replace NULL values with some characters.
